### PR TITLE
ci: machine type from e1 to f1

### PR DESCRIPTION
**Pull request by d-goncalves**

### CODE REVIEW

**Review by p-nilsson — APPROVED** [review]

**Comment by d-goncalves** [comment]
@OpsBotPrime merge on friday

**Comment by OpsBotPrime** [comment]
Pull request approved for merge by @d-goncalves, rebasing now.

**Comment by OpsBotPrime** [comment]
Rebased as 023a7fff6d283492f629b6e1272453d1d4385651, waiting for CI …

**Comment by OpsBotPrime** [comment]
[CI job :yellow_circle:](https://channable.semaphoreci.com/workflows/9d92a449-39d5-4933-94c6-27097a82bddf?pipeline_id=a9e2ca77-4533-47e2-83b9-87ae00857f15) started.

**Pull request merged**
